### PR TITLE
added DFS.cpp which contain DFS traversal algorithm

### PR DESCRIPTION
**Pull request by Akash82228**
hey! check this one out i implemented DFS algo in it great learning🏆

### CODE REVIEW

**Comment by yashrajdesai** [comment]
Please mention the issue number in the PR description.

**Comment by Akash82228** [comment]
its 9 th in the issue list and #22 is written named by DFS

**Comment by Akash82228** [comment]
#22

**Comment by yashrajdesai** [comment]
Okay, in your future PRs mention the issue number in the PR description itself as it becomes easier for us to keep track of issues.🙂

**Pull request merged**
