### PR TITLE
Crpyto-Tracker-App

### PR DESCRIPTION
**Pull request by HarshBaldaniya**
IN THIS REACT APP
- I used coingecko.com - The Most Comprehensive Cryptocurrency API.
- I used a search bar for search Cryptocurrency with a nice hover effect
BIT1
BIT2
.

### CODE REVIEW

**Comment by yashrajdesai** [comment]
Please mention the steps to install and run the project locally so that we can test it.

**Comment by HarshBaldaniya** [comment]
@yashrajdesai

**Comment by yashrajdesai** [comment]
@HarshBaldaniya the "Crpyto-Tracker-App" folder is empty. Please add the files containing the code.

**Comment by HarshBaldaniya** [comment]
Ok sir, I will push again 
Thanks sir.

**Comment by yashrajdesai** [comment]
Closing this PR as #102 is merged.

**Pull request closed without merging**
